name: omorisai-cms
services:
  payload:
    image: node:20-alpine
    container_name: omorisai-cms-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - omorisai-cms-network

  mongo:
    image: mongo:latest
    container_name: omorisai-cms-mongo
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - omorisai-cms-network

  build-service:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: omorisai-build-service
    volumes:
      - ./out:/app/out
      - ./:/app/source
    networks:
      - omorisai-cms-network
    command: sh -c "tail -f /dev/null"
    restart: unless-stopped

volumes:
  data:
  node_modules:

networks:
  omorisai-cms-network:
    driver: bridge