name: oomorisai-cms
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oomorisai-cms-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.prod
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: oomorisai-cms-mongo
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data: 