name: omorisai-cms
services:
  payload:
    image: node:20-alpine
    container_name: omorisai-cms-app
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - omorisai-cms-network
      - default

  mongo:
    image: mongo:latest
    container_name: omorisai-cms-mongo
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - omorisai-cms-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: omorisai-cms-cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    networks:
      - omorisai-cms-network

networks:
  omorisai-cms-network:
    driver: bridge
  default:
    driver: bridge

volumes:
  data:
  node_modules: 
